name: Test using an env secret in R script

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:      
  test-secret:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          ref: main
          
      - name: set env var
        shell: bash
        env:
          SECRET_MSG: ${{secrets.TEST_SECRET}}
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          sudo apt-get install libcurl4-openssl-dev
          Rscript -e 'install.packages(c("utils"))'
          
      - name: Run test_secret.R
        run: |
          Rscript -e "source('scripts/test_secret.R')"
